import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import dataproduct from "../database/dummyproducts";
import ProductCard from "../components/ProductCard";

const current_user_id = 100;

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Sasta Amazon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className="conainer">
          {dataproduct.map((obj: any) => {
            return (
              <Link
                href="/product/[obj.productid]"
                as={`/product/${obj.productid}`}
              >
                <div className="card">
                  <ProductCard data={obj} />
                </div>
              </Link>
            );
          })}
        </div>
      </main>
      <style>
        {`
  .conainer{
    width:100vw;
    display:flex;
    flex-align:horizontal;
    flex-wrap:wrap;
    align-items:center;
    justify-content:center;

  }
  .card{
    margin:1rem;
  }
`}
      </style>
    </div>
  );
};

export default Home;
