// main page

// Modules
import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

// Components
import dataproduct from "../database/dummyproducts";
import ProductCard from "../components/ProductCard";
import { useState } from "react";
import { Button } from "@mantine/core";
// Main
const Home: NextPage = () => {
  const [dark, setDark] = useState(true);

  return (
    <div className={styles.container}>
      <Head>
        <title>B4Buy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="header">
        <Button
          onClick={() => {
            setDark(!dark);
          }}
          color={dark ? "blue" : "red"}
          style={{
            position: "fixed",
            top: "10px",
            right: "10px",
          }}
        >
          {dark ? "light" : "dark"}
        </Button>
        <h1>B4Buy</h1>
      </div>
      <main className={!dark ? styles.main : `${styles.main} dark`}>
        <div className="conainer">
          {/* Iterate over producs and return its cards along withs its unique dynamic product page link*/}
          {dataproduct.map((obj: any, key: number) => {
            return (
              <Link
                href="/product/[obj.productid]"
                as={`/product/${obj.productid}`}
                key={key}
              >
                <div className="card" key={key}>
                  <ProductCard data={{ ...obj, dark }} />
                </div>
              </Link>
            );
          })}
        </div>
      </main>
      <style>
        {`
  .conainer{
    padding-top: 10vh;
    width:100w;
    display:flex;
    flex-align:row;
    justify-content:center;
    align-items:center;
    flex-wrap:wrap;
  }
  .card{
    margin:1rem;
    height:40rem;
    width: 40rem;
  }
  .header{
    width:100vw;
    height:10vh;
    background-color:black;
    position:fixed;
    top:0;
    left:0;
    z-index:100;
  }
  .header h1{
    margin-left: 2rem ;
    color:white;
  }
  
`}
      </style>
    </div>
  );
};

export default Home;
